services:
    ros2_humble:
      build:
        context: .
        dockerfile: Dockerfile
      image: ros2_humble_privileged:latest
      container_name: ros2_humble_privileged
      privileged: true
      network_mode: host
      ipc: host
      pid: host
      stdin_open: true
      tty: true
      environment:
        DISPLAY: ${DISPLAY}
        QT_X11_NO_MITSHM: "1"
        ROS_DOMAIN_ID: "0"
        RMW_IMPLEMENTATION: rmw_fastrtps_cpp
      volumes:
        - ../:/workspaces/Arm_Project
        - /tmp/.X11-unix:/tmp/.X11-unix:rw
        - /dev:/dev
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
      working_dir: /workspaces/Arm_Project
      command: bash

